# Generated by Django 5.0.3 on 2024-04-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=122)),
                ('productDescription', models.CharField(max_length=122)),
                ('productPrice', models.CharField(max_length=122)),
            ],
        ),
    ]
